# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gavin McGimpsey
email: dev@gavinmcg.com
description: > # this means to ignore newlines until "baseurl:"
    Gavin McGimpsey's Site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.gavinmcg.com" # the base hostname & protocol for your site
github_username:  gavinmcgimpsey

# Build settings
encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
